args<-commandArgs(TRUE)
package_root<-normalizePath(args[1],winslash='/',mustWork=TRUE)
out<-normalizePath(args[2],winslash='/',mustWork=TRUE)
.libPaths(c(strsplit(Sys.getenv('R_LIBS_USER'),.Platform$path.sep,fixed=TRUE)[[1]],.libPaths()))
capture.output({print(R.version.string);print(RNGkind());print(.libPaths());sessionInfo()},file=file.path(out,'environment_sessionInfo.txt'))
stopifnot(as.character(getRversion())=='4.5.2')
expected<-read.csv(file.path(package_root,'environment/package-versions.csv'))
actual<-data.frame(package=expected$package,version=vapply(expected$package,function(p)as.character(packageVersion(p)),character(1)),path=vapply(expected$package,find.package,character(1)))
write.csv(actual,file.path(out,'environment_actual.csv'),row.names=FALSE)
capture.output({print(R.version.string);print(RNGkind());print(.libPaths());sessionInfo()},file=file.path(out,'environment_sessionInfo.txt'))
stopifnot(identical(as.character(actual$version),as.character(expected$version)))
for(p in c('haven','xml2','rvest','dplyr','jsonlite'))stopifnot(requireNamespace(p,quietly=TRUE))
cat('ENVIRONMENT_EXACT_VERSION_CHECK = PASS\n')
